### ISSUE TITLE
Dimensionality in Interface

### ISSUE THREAD

**Issue by RolandStolz** [wetzlingerm/continuoussets#1]
It would be great to have an interface method / property / attribute for the dimensionality of the set.
Some methods are implemented as if there is one, e.g.
```
elif max(subspace) >= self.dimension:
```
in `_checkSubSpace` line 173.
However, this is not defined, so my IDE complains about it all the time.

**Comment by wetzlingerm** [comment]
Fixed in commit [3ebdd7b](https://github.com/wetzlingerm/continuoussets/commit/3ebdd7b071b985e390cba14719b2952f86380368): `dimension` is now, among others, a method in `IConvexSet`.
