### ISSUE TITLE
support function

### ISSUE THREAD

**Issue by moritzKoebe** [wetzlingerm/continuoussets#2]
support function doesnt work correctly
![image](https://github.com/user-attachments/assets/9c95e551-6684-4755-b2d3-55b881221f88)
should be root(2) = 1.41... but is 2.0

**Comment by moritzKoebe** [comment]
correct support function for polytope: 
    def _temp_support_function_polytope(self, poly: HPolyhedron, v: np.ndarray):
        if poly is None:
            return 0
        v /= np.linalg.norm(v)
        distances = np.dot(poly.vertices(), v)
        return np.max(distances)

**Comment by wetzlingerm** [comment]
The support function `rho` for a compact and convex set `S` and a direction `l` is defined as [1, Figure 1.6.4]
```
rho(S,l) = max_{s \in S} l^T s
```
In your example, the maximum is reached at (the support vector) `s* = [1,1]`, and the dot product `l^T s*` equals `2.0`.
Hence, the current implementation is correct as is.

If you want the result to be the square root of 2 -- which can be used, e.g., for measuring distances -- please normalize the direction before calling `support_function`, as you did in the code above.

---
[1] D. P. Bertsekas. "Convex Optimization Theory," Athena Scientific, Belmont, Massachusetts. (see here: http://web.mit.edu/dimitrib/www/Convex_Theory_Entire_Book.pdf)
